//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXGL.OA.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string text { get; set; }
        public string url { get; set; }
        public string iconCls { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public string HttpMethod { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string ReMark { get; set; }
    }
}
